# docker-compose.yml
version: "3.8"
services:
  postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: cscc09-project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:123456@postgres:5432/cscc09-project # Connect to 'postgres' service name
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist/project-reactenjoyerz/browser:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
